name: wasmdemo

on: [pull_request]

jobs:
  build_and_test_desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Prerequisites
        run: sudo apt-get install cmake ninja-build

      - name: Cmake Configure (Debug)
        run: cmake -S . -B build_debug -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Cmake Build (Debug)
        run: cmake --build build_debug --verbose

      - name: CTest (Debug)
        run: ctest --test-dir build_debug --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: build_output
          path: |
            build_debug/cpp/wasmdemo_test
